name: Gemin AI Code Tester CI Pipeline

on:
  workflow_dispatch: # Enables the manual trigger button
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'gemini_env'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: gemini_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright browsers
        run: |
          pip install playwright
          playwright install --with-deps

      # This step handles running the script using the available secret configurations
      - name: Run main.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          Headless: ${{ vars.HEADLESS }}
          # This fallback syntax ensures it tries secrets first, then variables
          # AI_MODEL: '${{ secrets.AI_MODEL }}'
        run: |
          python main.py
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Testing_Screenshots
          path: Screenshots/**